name: influxdb-paged-export
dependencies:
- openssl=1.0.2d=0
- pip=7.1.2=py27_0
- python=2.7.10=2
- readline=6.2=2
- setuptools=18.4=py27_0
- sqlite=3.8.4.1=1
- wheel=0.26.0=py27_1
- zlib=1.2.8=0
- pip:
  - certifi==2017.4.17
  - chardet==3.0.4
  - click==6.7
  - idna==2.5
  - influxdb==4.1.1
  - python-dateutil==2.6.1
  - pytz==2017.2
  - requests==2.18.1
  - six==1.10.0
  - urllib3==1.21.1

